# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VivadoProject/MobileCharger/MobileCharger.cache/wt [current_project]
set_property parent.project_path F:/VivadoProject/MobileCharger/MobileCharger.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/VivadoProject/MobileCharger/MobileCharger.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/PosedgeShift.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/DelayPosedge.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/TimeCountDown.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/TensTimer.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/StartButton.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/SlakeCol.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/Shift.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/PreKey.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/Money_Time.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/DISP_Select.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/DISP_Scan.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/CoreState.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/KeyDriver.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/FreqDiv.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/DISP.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/ControlCircuit.v
  F:/VivadoProject/MobileCharger/MobileCharger.srcs/sources_1/new/MobileCharger_TOP.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/VivadoProject/MobileCharger/MobileCharger.srcs/constrs_1/new/MoblieCharger_PIN.xdc
set_property used_in_implementation false [get_files F:/VivadoProject/MobileCharger/MobileCharger.srcs/constrs_1/new/MoblieCharger_PIN.xdc]


synth_design -top MobileCharger_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef MobileCharger_TOP.dcp

catch { report_utilization -file MobileCharger_TOP_utilization_synth.rpt -pb MobileCharger_TOP_utilization_synth.pb }
